# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-04-21 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '__first__'),
        ('acknowledgements', '__first__'),
        ('products', '__first__'),
        ('projects', '__first__'),
        ('media', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_files', to='media.S3Object')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trcloud_id', models.IntegerField(default=0, null=True)),
                ('trcloud_document_number', models.TextField(default=b'', null=True)),
                ('company', models.TextField(default=b'Alinea Group Co., Ltd.')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('_due_date', models.DateTimeField(db_column=b'due_date', null=True)),
                ('status', models.TextField(db_column=b'status', default=b'open')),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('fob', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('calendar_event_id', models.TextField(null=True)),
                ('vat', models.IntegerField(default=0)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.IntegerField(default=0)),
                ('second_discount', models.IntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('second_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('post_discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acknowledgements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='acknowledgements.Acknowledgement')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='contacts.Customer')),
                ('employee', models.ForeignKey(db_column=b'employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(related_name='invoice', through='invoices.File', to='media.S3Object')),
                ('pdf', models.ForeignKey(db_column=b'pdf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.S3Object')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.Phase')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.Project')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trcloud_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(db_column=b'status', default=b'invoiced', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('acknowledgement_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='acknowledgements.Item')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='media.S3Object')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.Invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='products.Product')),
            ],
            options={
                'permissions': (('change_item_price', 'Can edit item price'),),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='administrator.Log')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='invoices.Invoice')),
            ],
            bases=('administrator.log',),
        ),
        migrations.AddField(
            model_name='file',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
