# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acknowledgements', '__first__'),
        ('estimates', '0004_auto_20160507_0222'),
        ('contacts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('acknowledgement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='acknowledgements.Acknowledgement')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='contacts.Contact')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Customer')),
                ('quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estimates.Estimate')),
            ],
        ),
    ]
