# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='last_contacted',
            field=models.DateField(default=datetime.date(2016, 5, 7)),
        ),
        migrations.AddField(
            model_name='deal',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
