# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20160507_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deal',
            name='last_contacted',
            field=models.DateField(default=datetime.date(2016, 5, 8)),
        ),
    ]
