# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-05-30 15:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '__first__'),
        ('invoices', '0001_initial'),
        ('acknowledgements', '__first__'),
        ('media', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_files', to='media.S3Object')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trcloud_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(db_column=b'status', default=b'paid', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('invoice_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='invoices.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='administrator.Log')),
            ],
            bases=('administrator.log',),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.IntegerField(default=0)),
                ('company_name', models.TextField(default=b'Alinea Group Co., Ltd.')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('paid_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.TextField(default=b'paid')),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('calendar_event_id', models.TextField(null=True)),
                ('vat', models.IntegerField(default=0)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount', models.IntegerField(default=0)),
                ('second_discount', models.IntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('second_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('post_discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('acknowledgement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='acknowledgements.Acknowledgement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Company')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='contacts.Customer')),
                ('employee', models.ForeignKey(db_column=b'employee_id', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(related_name='receipt', through='receipts.File', to='media.S3Object')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='invoices.Invoice')),
                ('pdf', models.ForeignKey(db_column=b'pdf', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.S3Object')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='receipts.Receipt'),
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.Receipt'),
        ),
        migrations.AddField(
            model_name='file',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.Receipt'),
        ),
    ]
