# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.django_orm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key_id', models.TextField(default=b'')),
                ('secret_access_key', models.TextField(default=b'')),
                ('iam_id', models.TextField(default=b'')),
            ],
        ),
        
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserLog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='awsuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aws_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
